// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7jFPVbu27CAJ7GdyRQu1aH-Mzz02gpU',
    appId: '1:490864973661:web:44c7cbe49bea1035467ab4',
    messagingSenderId: '490864973661',
    projectId: 'smart-village-8b29b',
    authDomain: 'smart-village-8b29b.firebaseapp.com',
    storageBucket: 'smart-village-8b29b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7M3i19YCkoupdrDJNZ100WW5ph-uDCs',
    appId: '1:490864973661:android:c0036f75dd44c9e9467ab4',
    messagingSenderId: '490864973661',
    projectId: 'smart-village-8b29b',
    storageBucket: 'smart-village-8b29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO73R-rFaCmyB2W9U8sk4NHX4eMaZv1cs',
    appId: '1:490864973661:ios:daf86acf91f040ab467ab4',
    messagingSenderId: '490864973661',
    projectId: 'smart-village-8b29b',
    storageBucket: 'smart-village-8b29b.appspot.com',
    iosBundleId: 'com.example.smartVillage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO73R-rFaCmyB2W9U8sk4NHX4eMaZv1cs',
    appId: '1:490864973661:ios:6953ea69c0a35116467ab4',
    messagingSenderId: '490864973661',
    projectId: 'smart-village-8b29b',
    storageBucket: 'smart-village-8b29b.appspot.com',
    iosBundleId: 'com.example.smartVillage.RunnerTests',
  );
}
